# traefik reverse proxy config
# docs: https://doc.traefik.io/traefik/

[api]
  dashboard = true
  insecure = true

[log]
  level = "INFO"

[providers]
  [providers.docker]
    endpoint = "unix:///var/run/docker.sock"
    exposedByDefault = false

[entryPoints]
  [entryPoints.web]
    address = ":80"
    [entryPoints.web.http]
      [entryPoints.web.http.redirections]
        [entryPoints.web.http.redirections.entryPoint]
          to = "websecure"
  [entryPoints.websecure]
    address = ":443"
  [entryPoints.dashboard]
    address = ":8080"

[certificatesResolvers]
  [certificatesResolvers.retropilot]
    [certificatesResolvers.retropilot.acme]
      caServer = "https://acme-v02.api.letsencrypt.org/directory"
      email = "admin@retropilot.org"
      storage = "acme.json"
      [certificatesResolvers.retropilot.acme.httpChallenge]
        entryPoint = "web"
